### ISSUE TITLE
Support for 'extended' regexes.

### ISSUE THREAD

**Issue by pbuetow** [mimecast/dtail#11]
The Golang regex engine is a bit limited. It would be good to add the following new behaviour to DTail:

1. The current way `--regex "REGEX"` stays as is.
2. Add a new "perl" style syntax, whereas `!/` or `/` in the beginning of the regex identifies an extended DTail regex. As a start it could allow the `!/` modifier (inverse regex) and the `/i`modifier (case insensitive). An example would be `--regex "/REGEX1/i and !/REGEX2/ or /REGEX3/`. This would allow to specify much more powerful patterns.

**Comment by snonux** [comment]
What needs to be done is 1. to set the Perl compatibility flag for Go regexp (it will not lead to full Perl regexp compatibility but closer) and 2. to add a new argument -nregex for negative matching to dtail.

**Comment by pbuetow** [comment]
Develop branch includes the following changes:

1. --invert option to negate the regex
2. --grep option as an alias to --regex

Furthermore, "perl" style regex are already enabled in Go. Not including the /-syntax as proposed in point 2 in this issue. But that is not required as of now. Examples in the docs will follow.

**Comment by snonux** [comment]
This issue can be closed.
